<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>TypingTutor-Setup</AssemblyName>
    <ApplicationIcon>..\..\Store\Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\Publish\FrameworkDependent\TypingTutor.exe">
      <Link>Payload\TypingTutor.exe</Link>
    </EmbeddedResource>
  </ItemGroup>

</Project>
